services:
  # Uncomment the following to use postgres
  postgres:
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
volumes:
  pgdata:
  node_modules:
